version: '3'
services:
  postgres:
    image: "postgres:latest"
    container_name: postgres
    hostname: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 2s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  rabbitmq:
    image: "rabbitmq:3"
    ports:
      - "5672:5672"

  orthanc:
    image: jodogne/orthanc-plugins
    container_name: orthanc-plugins
    ports:
      - "4242:4242"
      - "8042:8042"

volumes:
  postgres_data:
    driver: local