version: '3'
services:
  db:
    container_name: db
    image: "postgres:latest"
    environment:
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  hiu-db-setup:
    image: bahmnicovid19/hiu-db-initializer
    container_name: hiu-db-setup
    environment:
      - 'JAVA_TOOL_OPTIONS=-Djdbc.url=jdbc:postgresql://db:5432/health_information_user -Djdbc.username=postgres -Djdbc.password=welcome'
  hiu-ui:
    image: "bahmnicovid19/hiu-ui:latest"
    container_name: hiu-ui
    environment:
      BACKEND_BASE_URL: ${BACKEND_BASE_URL}
      BASE_NAME: ${BASE_NAME}
      BACKEND_API_PATH: ${BACKEND_API_PATH}
      DICOM_SERVER_PATH: ${DICOM_SERVER_PATH}
      VIEWER_PAGE: ${VIEWER_PAGE}
      TITLE: ${TITLE}
      TIMEZONE_OFFSET: ${TIMEZONE_OFFSET}
    ports:
      - "5000:5000"
  hiu:
    image: "bahmnicovid19/health-information-user:latest"
    environment:
      HIU_ID: ${HIU_ID}
      HIU_NAME: ${HIU_NAME}
      IDENTITY_JWK_URL: ${IDENTITY_JWK_URL}
      DATA_PUSH_URL: ${DATA_PUSH_URL}
      CONSENT_NOTIFICATION_URL: ${CONSENT_NOTIFICATION_URL}
      CONSENT_MANAGEMENT_SUFFIX: ${CONSENT_MANAGEMENT_SUFFIX}
      CONSENT_MANAGEMENT_URL: ${CONSENT_MANAGEMENT_URL}
      DEFAULT_PAGE_SIZE: ${DEFAULT_PAGE_SIZE}
      MAX_PAGE_SIZE: ${MAX_PAGE_SIZE}
      LOCAL_STORAGE_PATH: ${LOCAL_STORAGE_PATH}
      HIU_CLIENT_ID: ${HIU_CLIENT_ID}
      HIU_CLIENT_SECRET: ${HIU_CLIENT_SECRET}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      CONSENT_MANAGER_DB_NAME: ${CONSENT_MANAGER_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_CONNECTION_POOL_SIZE: ${DB_CONNECTION_POOL_SIZE}
      OFFSET_IN_DAYS: ${OFFSET_IN_DAYS}
      USING_GATEWAY: '${USING_GATEWAY}
      GATEWAY_BASE_URL: ${GATEWAY_BASE_URL}
      GATEWAY_REQUEST_TIMEOUT: ${GATEWAY_REQUEST_TIMEOUT}
      GATEWAY_JWK_URL: ${GATEWAY_JWK_URL}
      HFR_AFFINITY_DOMAINS: ${HFR_AFFINITY_DOMAINS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      MAX_IN_MEMORY_SIZE: ${MAX_IN_MEMORY_SIZE}
      DATA_FLOW_CONSENT_REQUEST_WAIT_TIME: ${DATA_FLOW_CONSENT_REQUEST_WAIT_TIME}
      DATA_FLOW_CONSENT_ARTEFACT_WAIT_TIME: ${DATA_FLOW_CONSENT_ARTEFACT_WAIT_TIME}
      DATA_FLOW_PART_WAIT_TIME: ${DATA_FLOW_PART_WAIT_TIME}
      BACKEND_BASE_URL: ${BACKEND_BASE_URL}
    ports:
      - "9053:8080"
      
 volumes:
      postgresql:
      postgresql_data:
