version: '3'
services:
  hiu:
    image: "projecteka/health-information-user:v1.3.2"
    environment:
      HIU_ID: Bahmni
      HIU_NAME: Bahmni
      DATA_PUSH_URL: "http://hiu:8003/data/notification"
      CONSENT_NOTIFICATION_URL: "http://localhost:8003/consent/notification"
      CONSENT_MANAGEMENT_SUFFIX: sbx
      CONSENT_MANAGEMENT_URL: "https://dev.ndhm.gov.in/cm"
      DEFAULT_PAGE_SIZE: 20
      MAX_PAGE_SIZE: 100
      LOCAL_STORAGE_PATH: /tmp/
      HIU_CLIENT_ID: SBX_000060
      HIU_CLIENT_SECRET: f638e735-67f7-4119-8ba6-8a2d26bcc3a4
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      CONSENT_MANAGER_DB_NAME: health_information_user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: welcome
      DB_CONNECTION_POOL_SIZE: 5
      OFFSET_IN_DAYS: 2
      USING_GATEWAY: 'true'
      GATEWAY_BASE_URL: "https://dev.ndhm.gov.in/gateway"
      GATEWAY_REQUEST_TIMEOUT: 2000
      GATEWAY_JWK_URL: "https://dev.ndhm.gov.in/gateway/v0.5/certs"
      HFR_AFFINITY_DOMAINS: facilitysbx.ndhm.gov.in
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      MAX_IN_MEMORY_SIZE: 500MB
      DATA_FLOW_CONSENT_REQUEST_WAIT_TIME: 1
      DATA_FLOW_CONSENT_ARTEFACT_WAIT_TIME: 1
      DATA_FLOW_PART_WAIT_TIME: 1440
    ports:
      - "9053:8080"
