version: '3'
services:
  hiu-db-setup:
    image: projecteka/hiu-db-initializer
    container_name: hiu-db-setup
    environment:
      - 'JAVA_TOOL_OPTIONS=-Djdbc.url=jdbc:postgresql://postgres:5432/health_information_user -Djdbc.username=postgres -Djdbc.password=password'
    depends_on:
      - postgres

  orthanc:
    image: jodogne/orthanc-plugins
    container_name: orthanc-plugins
    ports:
      - "4242:4242"
      - "8042:8042"

volumes:
  postgres_data:
    driver: local