apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiu
  namespace: nha-app
  labels:
    app: hiu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hiu
  template:
    metadata:
      labels:
        app: hiu
    spec:
      initContainers:
        - name: hiu-db-migrator
          image: projecteka/hiu-db-initializer:latest
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Djdbc.url=jdbc:postgresql://nhadcl-postges-1.nhadclmgm.tatacommunications.com:5633/health_information_user -Djdbc.username=postgres -Djdbc.password=TAta12#$"
      containers:
        - name: hiu
          image: ganesan92/health-information-user:64b1fb5
          imagePullPolicy: Always
          env:
            - name: CENTRAL_REGISTRY_JWK_URL
              value: http://client-registry:8080/certs
            - name: CENTRAL_REGISTRY_URL
              value: http://client-registry:8080
            - name: CONSENT_MANAGEMENT_SUFFIX
              value: '@ncg'
            - name: CONSENT_MANAGEMENT_URL
              value: http://consent-manager:8000
            - name: CONSENT_MANAGER_DB_NAME
              value: health_information_user
            - name: CONSENT_NOTIFICATION_URL
              value: http://hiu:8003/consent/notification
            - name: DATA_PUSH_URL
              value: http://hiu:8003/data/notification
            - name: DB_CONNECTION_POOL_SIZE
              value: "5"
            - name: DEFAULT_PAGE_SIZE
              value: "20"
            - name: GATEWAY_BASE_URL
              value: http://gateway:8000/v1
            - name: GATEWAY_REQUEST_TIMEOUT
              value: "8000"
            - name: HIU_CLIENT_ID
              value: "10000002"
            - name: HIU_CLIENT_SECRET
              value: 81dda649-1376-472a-bbfd-7adf419e0c8b
            - name: HIU_ID
              value: "10000002"
            - name: HIU_NAME
              value: Max Health Care
            - name: LOCAL_STORAGE_PATH
              value: /tmp/
            - name: MAX_IN_MEMORY_SIZE
              value: 500MB
            - name: MAX_PAGE_SIZE
              value: "100"
            - name: OFFSET_IN_DAYS
              value: "2"
            - name: ORTHANC_PASSWORD
              value: orthanc
            - name: ORTHANC_SERVER_URL
              value: http://orthanc:8042
            - name: ORTHANC_USERNAME
              value: orthanc
            - name: POSTGRES_HOST
              value: nhadcl-postges-1.nhadclmgm.tatacommunications.com
            - name: POSTGRES_PASSWORD
              value: "TAta12#$"
            - name: POSTGRES_PORT
              value: "5633"
            - name: POSTGRES_USER
              value: postgres
            - name: USING_GATEWAY
              value: "true"
            - name: GATEWAY_JWK_URL
              value: http://gateway:8000/v1/certs
            - name: RABBITMQ_HOST
              value: rabbitmq.nhadclmgm.tatacommunications.com
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME 
              value: admin
            - name: RABBITMQ_PASSWORD
              value: "TA7a3@!"
          ports:
            - name: http
              containerPort: 8003
              protocol: TCP
