apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  HIU_CLIENT_ID: {{ .Values.secrets.HIU_CLIENT_ID | b64enc | quote }}
  HIU_CLIENT_SECRET: {{ .Values.secrets.HIU_CLIENT_SECRET | b64enc | quote }}
