apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  HIU_CLIENT_ID: {{ .Values.secrets.HIU_CLIENT_ID | b64enc | quote }}
  HIU_CLIENT_SECRET: {{ .Values.secrets.HIU_CLIENT_SECRET | b64enc | quote }}
  POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc | quote }}
  RABBITMQ_USERNAME: {{ .Values.secrets.RABBITMQ_USERNAME | b64enc | quote }}
  RABBITMQ_PASSWORD: {{ .Values.secrets.RABBITMQ_PASSWORD | b64enc | quote }}
